apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobmate-frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: jobmate-frontend
        image: gireesagar/jobmate-frontend:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
