apiVersion: v1
kind: Service
metadata:
  name: jobmate-frontend-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
