apiVersion: v1
kind: Service
metadata:
  name: jobmate-frontend-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80     # Port exposed by the service
      targetPort: 80 # Port your container is listening on
      nodePort: 30000
  type: NodePort  # You can change this to NodePort or LoadBalancer if needed
