apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobmate
spec:
  selector:
    matchLabels:
      version: v1           # Pod label to be used by Service to select the pods from this deployment
  replicas: 5                 # number of replica of the Pods
  template:
    metadata:
      labels:
        env: dev         # Pod's label
        app: jobmate
        version: v1
    spec:
      containers:
      - name: frontend
        image: gireesagar/jobmate-frontend:v1    # which image it will use
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 80     # Port exposed by container inside the Pod
       