apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobmate-backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: jobmate-backend
        image: gireesagar/jobmate-backend:v1
        env:
        - name: DATABASE_URL
          value: "pgurl"
        - name: SECRET_KEY
          value: "key"
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "30"
        - name: UPLOADS_DIR
          value: "uploads"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
